### PR TITLE
Add ability to specify point settings

### PR DESCRIPTION
**Pull request by egeriis**
Will pass object passed to `point` through to C3.

### CODE REVIEW

**Comment by jeff-phillips-18** [comment]
+1

**Comment by renaekathleen** [comment]
+1, was just about to create a PR for the same.

**Comment by Glavin001** [comment]
Thanks for contributing!

**Comment by jeff-phillips-18** [comment]
It doesn't appear the build was made with this PR. lib.js does not include this fix.

**Comment by Glavin001** [comment]
Could someone submit a Pull Request with the above fixes that @jeff-phillips-18 mentioned. I will review and merge that, too. Thanks.

**Comment by jeff-phillips-18** [comment]
Created the PR. Thanks.

**Comment by Glavin001** [comment]
Merged :+1:. Thanks!

**Pull request merged**
