### PR TITLE
Consume c3.js via ember-c3-shim instead of using global

### PR DESCRIPTION
**Pull request by mike-north**

### CODE REVIEW

**Comment by Glavin001** [comment]
Thanks! I'll try this out over the weekend. Looks good at first glance though.

**Comment by mike-north** [comment]
Thanks @Glavin001 - please let me know if you have any questions. I'm trying to get all of the ember D3/C3 addons using the same shims, to avoid duplicating imports into the asset pipeline.

**Comment by Glavin001** [comment]
I apologize for not merging this sooner. If you could resolve the merge conflicts I will happy merge and test today. Thank you for contributing!

**Comment by myared** [comment]
@mike-north still considering this? happy to help out if you'd like.

**Comment by mike-north** [comment]
@myared sold

**Comment by AO16** [comment]
This has been included in #52

**Pull request closed without merging**
