### PR TITLE
 update ember/ember-cli versions 

### PR DESCRIPTION
**Pull request by yratanov**
* use c3 from npm
* fix import warnings
* fix issued when _reload was called on a component in destrpyed/isDestroying state
* fix animation glitch because didReceiveAttrs is called every time attrs update
* remove all bower dependencies except of jsoneditor

### CODE REVIEW

**Comment by yratanov** [comment]
@maxwondercorn 

**ember-cli-cjs-transform** is awesome! didn't know about it. Replaced ember-browserify with it.

**Comment by oakho** [comment]
Hey guys,

Any chance for you to merge this one soon ? I'm in the process to moving an app to ember 3 and would be nice to have an up to date version of this addon we are using in it !

Thanks

**Comment by maxwondercorn** [comment]
I thought I would have time to work on this all sooner but work and life got in the way.  Since 3.4 in now LTS we should be on v3.  I hope to get back to this in November, when I'll have a couple solid weekends to work on it.

**Comment by oakho** [comment]
No problem, I understand. Let me know if I can help in anyway. Thanks.

**Comment by Paskalouis** [comment]
Hi,
I am happy that this PR is still up.
Will this PR will be merged soon? @Glavin001 
@maxwondercorn are you working to continue things on this PR?

Thank you !

**Comment by maxwondercorn** [comment]
See issue #77

**Pull request merged**
